version: "3"
services:
  app:
    image: infoscreen:latest
    network_mode: host
    volumes:
      - ../:/home/churchtools_infoscreen
    container_name: infoscreen
    command: flask run --debug
    restart: always